<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net48;net10.0</TargetFrameworks>
    <LangVersion>5</LangVersion>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Identity.Client" Version="4.82.1" />
    <PackageReference Include="Microsoft.Identity.Client.Extensions.Msal" Version="4.82.1" />
    <PackageReference Include="Microsoft.SharePointOnline.CSOM" Version="16.1.26914.12004" />
    <PackageReference Include="System.Text.Json" Version="8.0.5" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net48'">
    <PackageReference Include="Fody" Version="6.9.3" PrivateAssets="all" />
    <PackageReference Include="Costura.Fody" Version="6.0.0" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <!-- MockSpoServerProgram を除外 -->
    <Compile Remove="MockSpoServerProgram.cs" />
  </ItemGroup>

</Project>
